### ISSUE TITLE
Automatizacion del proceso de preparacion del entorno AndroidStudio independiente del SO

### ISSUE THREAD

**Issue by JavideBaza** [IV-2014/VirtualBoard#35]

**Comment by JavideBaza** [comment]
Ya le estoy dando a esto gente! @angeljcc @divadcr @edupg1 @marquina91

**Comment by marquina91** [comment]
en que lo vas a hacer?

He estado mirando lo del testeo: http://docs.busterjs.org/en/latest/node-testing/#running-tests  que te parece?

**Comment by JavideBaza** [comment]
En el proceso de preparacion del entorno AndroidStudio. Esta bien para node.js pero mirate tambien de Android y de PHP, para que lo hagamos sobre lo que va a funcionar. Crea un issue diferente para eso y lo vamos viendo
