### ISSUE TITLE
Tests Android

### ISSUE THREAD

**Issue by edupg1** [IV-2014/VirtualBoard#36]

**Comment by edupg1** [comment]
Aqui vamos escribiendo lo que vayamos encontrando!! @angeljcc @divadcr @JavideBaza  @marquina91

**Comment by edupg1** [comment]
http://magmax.org/blog/2012/07/09/java-unit-test/

**Comment by JavideBaza** [comment]
Me pongo con este antes de darle al tema la automatización

**Comment by edupg1** [comment]
antes de ponerte a testear, vamos a poner alternativas y hacerlo de diferentes maneras!!

**Comment by edupg1** [comment]
http://www.vogella.com/tutorials/JUnit/article.html

**Comment by marquina91** [comment]
esto esta muy bien para poder hacer y usar las clases para nuestros test
http://developer.android.com/reference/android/test/package-summary.html
