### ISSUE TITLE
Tests PHP

### ISSUE THREAD

**Issue by edupg1** [IV-2014/VirtualBoard#37]

**Comment by edupg1** [comment]
http://writecodeonline.com/php/ Para testear código php online!!

**Comment by edupg1** [comment]
ya hay una manera de testear php!! busquemos más!!

**Comment by edupg1** [comment]
https://phpunit.de/manual/current/en/

**Comment by edupg1** [comment]
https://netbeans.org/kb/docs/php/phpunit.html

**Comment by edupg1** [comment]
Esta parte me la pido yo para hacerla!! pero seguir poniendo enlaces para realizar test de diferente manera en php.

**Comment by divadcr** [comment]
wtf

**Comment by edupg1** [comment]
http://right-handed-monkey.blogspot.com.es/2012/09/setting-up-phpunit-with-xampp.html

**Comment by edupg1** [comment]
http://www.programania.net/desarrollo-agil/pruebas-unitarias-y-funcionales-en-php/

**Comment by JavideBaza** [comment]
Edusss !! Que es el composer.json que subiste ayer??

**Comment by edupg1** [comment]
eso sale solo cuando metes el composer.phar

**Comment by angeljcc** [comment]
y donde está el composer.phar @edupg1 @JavideBaza

**Comment by edupg1** [comment]
el composer.phar esta en la carpeta php, luego la tienes que introducir en phpunit
