### ISSUE TITLE
Instalar y correr servidor web en un contenedor docker

### ISSUE THREAD

**Issue by divadcr** [IV-2014/VirtualBoard#40]
Documentación a seguir para realizar la instalación y hacer funcionar un servidor web mediante un contenedor docker
[Referencia 1](http://slopjong.de/2014/09/17/install-and-run-a-web-server-in-a-docker-container/)
[Referencia 2](https://medium.com/dev-tricks/apache-and-php-on-docker-44faef716150)

**Comment by angeljcc** [comment]
me pongo a ello

**Comment by angeljcc** [comment]
creo que se podria cerrar @JavideBaza @edupg1 @divadcr @marquina91
