### ISSUE TITLE
Aprovisionamiento - Ansible

### ISSUE THREAD

**Issue by angeljcc** [IV-2014/VirtualBoard#48]

**Comment by angeljcc** [comment]
Falta para que cree la base de datos que se e ha pasado XD

**Comment by JavideBaza** [comment]
Ya la estoy haciendo yo @angeljcc

**Comment by JavideBaza** [comment]
Gente, no he conseguido que se cree la tabla dentro de la base de datos, mañana seguiré viéndolo a ver si doy con la tecla

**Comment by marquina91** [comment]
javi con la modificación fue?

**Comment by angeljcc** [comment]
pon @JavideBaza sino no se va a enterar
y no no fue porque tu estar volviendo a crear una BD que ya está creada

**Comment by JavideBaza** [comment]
Noo , la base de datos y user y passwor ya la crea, hace falta que cree la tabla, es lo unico que falta @marquina91

**Comment by marquina91** [comment]
ok @JavideBaza  pensaba que era por eso.

**Comment by edupg1** [comment]
@JavideBaza  @angeljcc  @marquina91  @divadcr  falta algo de el aprovisionamiento?

**Comment by angeljcc** [comment]
@edupg1 falta que ejecute el script para hacer las tablas de base de datos, llevo toda la tarde en ello

**Comment by edupg1** [comment]
@angeljcc dime que tengo que hacer y te hecho una mano!
