### ISSUE TITLE
Licencia

### ISSUE THREAD

**Issue by angeljcc** [IV-2014/VirtualBoard#49]
He pensado en un GPLV2, que decís?
@JavideBaza  @edupg1  @marquina91  @divadcr  Tenemos que ponerla ya!!!!

**Comment by JavideBaza** [comment]
Voy a mirar lo que es porque no tengo ni idea XD

**Comment by angeljcc** [comment]
pincha en el commit y ves la licencia @JavideBaza

**Comment by JavideBaza** [comment]
perfect, nos quedamos con esta ! @angeljcc

**Comment by angeljcc** [comment]
Doy por cerrado esto.
